version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5001
    expose:
      - 5001
    env_file:
      - .env
    ports:
      - 5001:5001
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - db
